# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='close',
            new_name='some',
        ),
        migrations.RenameField(
            model_name='something',
            old_name='Close_key',
            new_name='some_key',
        ),
    ]
