# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_auto_20160906_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
