# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_product_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
    ]
