# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0011_auto_20160912_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='map',
            name='brands',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Brand'),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
