# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0012_auto_20160914_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Brand'),
        ),
    ]
