# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160802_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='some',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_set', to='myapp.Something'),
        ),
    ]
